### PR TITLE
Add pathfinder to the OCP/K8S templates

### PR DESCRIPTION
**Pull request by carlosthe19916**
Adding pathfinder templates based on https://github.com/konveyor/tackle-pathfinder/blob/main/src/main/kubernetes/tackle-pathfinder.yaml

### CODE REVIEW

**Comment by jonathanvila** [comment]
On the Kubernetes script, there's a couple of elements `commented`. I know it's not part of this PR, but is there a reason to leave commented code ?

**Comment by jonathanvila** [comment]
Tested K8s script on minikube : deployment OK, UI working, pathfinder answering :+1:

**Comment by carlosthe19916** [comment]
> On the Kubernetes script, there's a couple of elements `commented`. I know it's not part of this PR, but is there a reason to leave commented code ?

The plan was to move the .yaml templates from `tackle-controls` to this repository without changing anything. The second step is to add the `pathfinder` templates to the .yaml files. And after that, we all can create PRs to enhance the definition of the templates... Removing the commented lines are out of the scope of this PR so let's leave it for any subsequent PR.

**Comment by jonathanvila** [comment]
> > On the Kubernetes script, there's a couple of elements `commented`. I know it's not part of this PR, but is there a reason to leave commented code ?
> 
> The plan was to move the .yaml templates from `tackle-controls` to this repository without changing anything. The second step is to add the `pathfinder` templates to the .yaml files. And after that, we all can create PRs to enhance the definition of the templates... Removing the commented lines are out of the scope of this PR so let's leave it for any subsequent PR.

One part of a PR is the #boyscout [rule](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch08.html#:~:text=Martin%20(Uncle%20Bob),the%20next%20group%20of%20campers.)  .....so unless there's a super rush to submit this PR, why not cleaning it ? 
In any case is your decision as you are the author.

**Comment by jonathanvila** [comment]
Tested Openshift template on crc : deployment OK, UI working, pathfinder answering :+1:

**Review by jonathanvila — APPROVED** [review]

**Pull request merged**
